export const const_url='https://stud.mgri.ru/'

export const API_AUTH = 'api/tokenauth'
export const API_COURSE = 'api/ElectronicEducation/Task?courseID='
export const API_DUTY = 'api/ElectronicEducation/ListCourseThemes?courseID='
export const API_MORE_INFO = 'api/UserInfo/Student?studentID=-'
export const API_ALL_COURSES='api/ElectronicEducation/ListCourse'
export const API_DETAIL_TASK = 'api/ElectronicEducation/TaskStudent?courseTaskID='
export const API_UPLOAD_FILE = 'api/ElectronicEducation/FileSave'
export const API_DELETE_FILE = 'api/ElectronicEducation/Files/deleteFile/'
export const API_CHECKER_MAIL = 'api/Mail/CheckMail'